WebApp/Models/Comment.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    public class Comment
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Bạn phải nhập nội dung bình luận")]
        public string Content { get; set; }
        public int AuthorId { get; set; }
        public Member Author{ get; set; }
        public int PostId { get; set; }
        public Post Post { get; set; }
        public DateTime DateCreate { get; set; }
    }
}

WebApp/Models/Post.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    public class Post
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập {0}")]
        [Display(Name ="Tên bài viết")]
        public string Title { get; set; }       
        [Required(ErrorMessage = "Bạn phải nhập {0}")]
        [Display(Name = "Nội dung")]
        public string Content { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateCreated { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DateModifier { get; set; }
        public bool IsActive { get; set; } = false;
        public bool IsDeleted { get; set; } = false;
        [Display(Name = "Danh mục")]
        public int CategoryId { get; set; }        
        public Category Category { get; set; }
        public int? AuthorId { get; set; }
        public Member Author { get; set; }
        public List<Comment> Comments { get; set; }
        public int CountView { get; set; }
        public string Thumbnail { get; set; }
    }
}

WebApp/Areas/Dashboard/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebApp.Controllers;
using WebApp.Interfaces;

namespace WebApp.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    public class CommentController : BaseController
    {
        public CommentController(IRepositoryManager repository) : base(repository)
        {
        }

        public async Task<IActionResult> Index()
        {
            var comments = (await _repository.Comment.GetComments()).OrderByDescending(p => p.DateCreate);           
            return View(comments);
        }
        public async Task<IActionResult> Delete(int id)
        {
            string token = User.FindFirstValue(ClaimTypes.Authentication);
            await _repository.Comment.DeleteComment(id, token);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Areas/Manage/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebApp.Controllers;
using WebApp.Interfaces;
using WebApp.Models;
using WebApp.Models.Response;

namespace WebApp.Areas.Dashboard.Controllers
{
    [Area("Manage")]
    [Authorize(Roles = "Admin,Moderator")]
    public class CommentController : BaseController
    {
        public CommentController(IRepositoryManager repository) : base(repository)
        {
        }

        public async Task<IActionResult> Index()
        {
            var comments = await _repository.Comment.GetComments(AccessToken);
            return View(comments);
        }
        public async Task<IActionResult> Delete(int id)
        {
            ResponseModel response = await _repository.Comment.DeleteComment(id, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã xóa bình luận"
                });
            }
            else
                HandleErrors(response);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Areas/Manage/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Controllers;
using WebApp.DataTransferObject;
using WebApp.Interfaces;
using WebApp.Models;
using WebApp.Models.Response;

namespace WebApp.Areas.Manage.Controllers
{
    [Area("Manage")]
    [Authorize(Roles = "Admin,Moderator")]
    public class PostController : BaseController
    {
        public PostController(IRepositoryManager repository) : base(repository)
        {
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            ListPostDto listPostDto = await _repository.Post.ManagerGetPosts(page, AccessToken);
            return View(listPostDto);
        }

        public async Task<IActionResult> NewPost(int page = 1)
        {
            ListPostDto listPostDto = await _repository.Post.GetNewPosts(page, AccessToken);
            return View(listPostDto);
        }

        public async Task<IActionResult> ListUnapproved(int page = 1)
        {
            ListPostDto listPostDto = await _repository.Post.GetUnapprovedPosts(page, AccessToken);
            return View(listPostDto);
        }
        public async Task<IActionResult> Approve(int id, string returnUrl = "")
        {
            ResponseModel response = await _repository.Post.Approve(id, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã phê duyệt bài viết"
                });
            }
            else
                HandleErrors(response);
            if (!string.IsNullOrEmpty(returnUrl))
                return Redirect(returnUrl);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> RemoveApproved(int id, string returnUrl = "")
        {
            ResponseModel response = await _repository.Post.RemoveApproved(id, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "warning",
                    Message = "Đã hủy bỏ phê duyệt bài viết"
                });
            }
            else
                HandleErrors(response);
            if (!string.IsNullOrEmpty(returnUrl))
                return Redirect(returnUrl);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            ResponseModel response = await _repository.Post.Delete(id, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "warning",
                    Message = "Đã xóa bài viết"
                });
            }
            else
                HandleErrors(response);
            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Restore(int id)
        {
            ResponseModel response = await _repository.Post.Restore(id, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "warning",
                    Message = "Đã khôi phục bài viết"
                });
            }
            else
                HandleErrors(response);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebApp.Interfaces;
using WebApp.Models;
using WebApp.Models.Response;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    public class CommentController : BaseController
    {
        public CommentController(IRepositoryManager repository) : base(repository)
        {
        }
        [HttpPost]
        public async Task<IActionResult> PostComment(Comment comment)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            comment.AuthorId = userId;
            comment.DateCreate = DateTime.UtcNow;
            ResponseModel response = await _repository.Comment.PostComment(comment, AccessToken);
            if (response is SuccessResponseModel)
            {
                return RedirectToAction("Detail", "Post", new { Id = comment.PostId }, "comments");
            }
            return BadRequest();
        }

        public async Task<IActionResult> Edit(int id)
        {
            Comment comment = await _repository.Comment.GetComment(id);            
            if (comment == null)
                return NotFound();
            if (int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)) != comment.AuthorId)
                return Unauthorized();
            return View(comment);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Comment comment)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            ResponseModel response = await _repository.Comment.EditComment(comment, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật bình luận"
                });
                return RedirectToAction("Detail", "Post", new { Id = comment.PostId }, "comments");
            }
            return BadRequest();
        }
        public async Task<IActionResult> Delete(int id)
        {
            Comment comment = await _repository.Comment.GetComment(id);
            if (comment == null)
                return NotFound();
            if (int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)) != comment.AuthorId)
                return Unauthorized();
            ResponseModel response = await _repository.Comment.DeleteComment(comment.Id, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type="success",
                    Message="Đã xóa bình luận"
                });
                return RedirectToAction("Detail", "Post", new { Id = comment.PostId }, "comments");

            }
            return BadRequest();
        }
    }
}

WebApp/Controllers/MemberController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebApp.Interfaces;
using WebApp.Models;
using WebApp.Models.Response;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    public class MemberController : BaseController
    {
        public MemberController(IRepositoryManager repository) : base(repository)
        {

        }

        public async Task<IActionResult> Index()
        {
            Member member = await _repository.Member.GetMemberById(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)), AccessToken);
            return View(member);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            Member member = await _repository.Member.GetMemberById(id);
            if (member == null)
                return NotFound();
            MemberDetailViewModel viewModel = new MemberDetailViewModel
            {
                Member = member,
                NumberOfComment = (await _repository.Comment.GetCommentsByMember(id)).Count,
                NumberOfPost = (await _repository.Post.GetPostsByMember(id)).Count
            };
            return View(viewModel);
        }

        public IActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel obj)
        {
            if (!ModelState.IsValid)
                return View();

            ResponseModel response = await _repository.Auth.ChangePassword(obj, AccessToken);            
            if (response is SuccessResponseModel)
            {
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật mật khẩu mới. Bạn cần đăng nhập lại."
                });
                return RedirectToAction("Login", "Account");
            }
            HandleErrors(response);
            return View();
        }

        public async Task<IActionResult> ListPost(int? id = null)
        {
            if (id == null)
                id = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            ListPostByMemberViewModel viewModel = new ListPostByMemberViewModel
            {
                Member = await _repository.Member.GetMemberById(id.Value),
                Posts = await _repository.Post.GetPostsByMember(id.Value, AccessToken)
            };
            return View(viewModel);
        }

        public async Task<IActionResult> ListComment(int? id = null)
        {
            if (id == null)
                id = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            ListCommentByMemberViewModel viewModel = new ListCommentByMemberViewModel
            {
                Member = await _repository.Member.GetMemberById(id.Value),
                Comments = await _repository.Comment.GetCommentsByMember(id.Value)
            };
            return View(viewModel);
        }
        public async Task<IActionResult> ChangeAboutMe()
        {
            Member member = await _repository.Member.GetMemberById(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)), AccessToken);
            return View(new ChangeAboutMeModel
            {
                MemberId = member.Id,
                AboutMe = member.AboutMe
            });
        }
        [HttpPost]
        public async Task<IActionResult> ChangeAboutMe(ChangeAboutMeModel obj)
        {
            if (!ModelState.IsValid)
                return View();
            ResponseModel response = await _repository.Member.ChangeAboutMe(obj, AccessToken);            
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật giới thiệu bản thân."
                });
                return RedirectToAction(nameof(Index));
            }
            HandleErrors(response);
            return View();
        }
        public IActionResult ChangeAvatar()
        {
            int memberId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            return View(new ChangeAvatarModel
            {
                MemberId = memberId,
            });
        }
        [HttpPost]
        public async Task<IActionResult> ChangeAvatar(ChangeAvatarModel obj)
        {            
            if (!ModelState.IsValid)
                return View();
            MultipartFormDataContent content = new MultipartFormDataContent();
            if (obj.AvatarUpload != null)
            {
                if(obj.AvatarUpload.Length > (1024 * 1024))
                {
                    ModelState.AddModelError(string.Empty, "Hãy chọn hình ảnh có kích thước nhỏ hơn 1MB");
                    return View();
                }
                content.Add(new StringContent(obj.MemberId.ToString()), nameof(obj.MemberId));
                content.Add(new StreamContent(obj.AvatarUpload.OpenReadStream()), nameof(obj.AvatarUpload), obj.AvatarUpload.FileName);
            }
            ResponseModel response = await _repository.Member.ChangeAvatar(content, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật hình đại diện."
                });
                return RedirectToAction(nameof(Index));
            }
            HandleErrors(response);
            return View();
        }
    }
}

WebApp/Views/Post/Delete.cshtml
@model Post
<nav id="breadcrumbs" class="breadcrumbs">
    <div class="container page-wrapper AllBreadcrumbs">
        <a asp-action="Index" asp-controller="Home" rel="homepage">Home</a>&nbsp;&nbsp;»&nbsp;&nbsp;
        <a asp-action="Index" asp-controller="Post" rel="post">Post</a>
        &nbsp;&nbsp;»&nbsp;&nbsp;
        Delete post
    </div>
</nav>
<!-- //breadcrumb -->

<div class="py-5 w3l-homeblock1 text-center">
    <div class="container mt-md-3 w3BlogLayout">
        <h3 class="blog-desc-big text-center mb-4">
            @Model.Title
        </h3>
        <div class="blog-post-align">

            <div class="blog-post-img">
                <a href="https://wp.w3layouts.com/designblog/author/w3layouts/">
                    <img src="~/images/328cc1f23e4a3b73aa60ee6ced1897a1(1).jpeg"
                         alt="" class="rounded-circle img-fluid">
                </a>
            </div>

            <div class="blog-post-info">
                <div class="author align-items-center mb-1">

                   <a class="url fn n"
                         asp-action="Detail" asp-controller="Member" asp-route-id="@Model.AuthorId">@Model.Author.Username</a>

                        in <a asp-action="Category" asp-controller="Post" asp-route-id="@Model.CategoryId" rel="category">@Model.CategoryId</a>

                    </div>
                    <ul class="blog-meta">

                        <li class="meta-item blog-lesson">
                            <span class="meta-value"> @Model.DateCreated.ToShortDateString() </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <section class="blog-post-main w3l-homeblock1">
        <!--/blog-post-->
        <div class="blog-content-inf pb-5">
            <div class="container pb-lg-4 w3BlogLayout">
                <div class="single-post-image mb-5">                   
                </div>
                <div class="single-post-content">
                    <!--post content-->
                    @Html.Raw(Model.Content)
                </div>
            </div>
        </div>

    </section>
    <div class="my-4">
        <form method="post">
            <input asp-for="Id" type="hidden" />
            <p class="text-center">Bạn có chắc chắn muốn xoá bài viết này?</p>
            <div class="d-flex">
                <button class="btn btn-danger mx-auto">Delete</button>
            </div>
        </form>
    </div>

WebApp/Views/Post/Detail.cshtml
@model Post
@inject IConfiguration configuration
@{ 
    var hostAddress = configuration.GetSection("ApiServer").Value;
}

<nav id="breadcrumbs" class="breadcrumbs">
    <div class="container page-wrapper AllBreadcrumbs">
        <a asp-action="Index" asp-controller="Home" rel="homepage">Home</a>&nbsp;&nbsp;»&nbsp;&nbsp;
        <a asp-action="Index" asp-controller="Post" rel="post">Post</a>
        &nbsp;&nbsp;»&nbsp;&nbsp;
        @Model.Title
    </div>
</nav>
<!-- //breadcrumb -->

<div class="py-5 w3l-homeblock1 text-center">
    <div class="container mt-md-3 w3BlogLayout">
        <h3 class="blog-desc-big text-center mb-4">
            @Model.Title
        </h3>
        <div class="blog-post-align">

            <div class="blog-post-img">
                <a href="https://wp.w3layouts.com/designblog/author/w3layouts/">
                    <img src="@(hostAddress + "/" + Model.Author.AvatarUrl)"
                         alt="@Model.Author.FullName" class="rounded-circle img-fluid">
                </a>
            </div>

            <div class="blog-post-info">
                <div class="author align-items-center mb-1">
                    <a class="url fn n"
                         asp-action="Detail" asp-controller="Member" asp-route-id="@Model.Author.Id">@Model.Author.Username</a>

                        in <a asp-action="Detail" asp-controller="Category" asp-route-id="@Model.CategoryId" rel="category">@Model.Category.Name</a>

                    </div>
                    <ul class="blog-meta">

                        <li class="meta-item blog-lesson">
                            <span class="meta-value"> At: @Model.DateCreated.ToShortTimeString() - @Model.DateCreated.ToShortDateString() </span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <section class="blog-post-main w3l-homeblock1">
        <!--/blog-post-->
        <div class="blog-content-inf pb-5">
            <div class="container pb-lg-4 w3BlogLayout">
                <div class="single-post-image mb-5">
                    <!--post's thumbnail-->                    
                    <!--</div>-->
                </div>
                <div class="single-post-content">
                    <!--post content-->
                    @Html.Raw(Model.Content)

                    <!--about author-->
                    <div class="author-card author-listhny my-lg-5 my-sm-4 w3ArticleAuth">
                        <div class="row">
                            <div class="author-left col-sm-3 mb-sm-0 mb-4">
                                <a asp-action="Detail" asp-controller="Member" asp-route-id="@Model.Author.Id">
                                    <!--author's avatar-->
                                    <img class="img-fluid"
                                         src="@(hostAddress+ "/" + Model.Author.AvatarUrl)"
                                         alt="@Model.Author.FullName">
                                </a>
                            </div>
                            <div class="author-right col-sm-9 position-relative align-self">

                                <h4>
                                    <a asp-action="Detail" asp-controller="Member" asp-route-id="@Model.Author.Id"
                                       class="title-team-28">@Model.Author.Username</a>
                                    @foreach (var role in Model.Author.Roles)
                                    {
                                        <span class="badge @role.ColorDisplay">@role.Name</span>
                                    }
                                </h4>
                                <p class="para-team mb-0">
                                    @Model.Author.AboutMe
                                </p>

                                <div class="share-icons mt-4">
                                    <a href="#">
                                        <span class="fa fa-twitter"></span>
                                    </a>

                                    <a href="#">
                                        <span class="fa fa-facebook"></span>
                                    </a>

                                    <a href="#">
                                        <span class="fa fa-instagram"></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--post's comments'-->
                    @if (Model.IsActive)
                    {
                        <div class="w3PostComments">
                            <div id="comments" class="comments-area">
                                @if (Model.Comments != null && Model.Comments.Count > 0)
                                {
                                    <div class="comments mt-5">
                                        <h4 class="side-title ">Comments (@Model.Comments.Count)</h4>
                                        <partial name="_Comments" model="@Model.Comments" />
                                    </div>
                                }
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <div class="leave-comment-form mt-5" id="reply">
                                        <div class="d-flex">
                                            <h4 class="side-title mb-2" id="reply-to-comment-title">Leave a Reply</h4>
                                            <a href="" id="cancel-reply-to-comment" class="ml-3 pt-2" hidden>Cancel</a>
                                        </div>
                                        @*<h4 class="side-title mb-2"></h4>*@
                                        <form asp-action="PostComment" asp-controller="Comment" method="post">
                                            <div class="form-group">
                                                <input type="hidden" name="PostId" value="@Model.Id" />
                                                <input type="hidden" name="CommentParentId" id="CommentParentId" value="" />
                                                <textarea name="Content" class="form-control" placeholder="Your Comment*" required
                                                          spellcheck="false"></textarea>
                                            </div>
                                            <div class="submit text-right">
                                                <button class="btn btn-style btn-primary">Post Comment </button>
                                            </div>
                                        </form>
                                    </div>
                                }
                                else
                                {
                                    <div class="text-center mt-3">
                                        Bạn phải <a asp-action="Login" asp-controller="Account">đăng nhập </a>
                                        mới có thể bình luận
                                    </div>
                                }
                            </div><!-- #comments -->
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>

WebApp/Views/Post/Index.cshtml
@model ListPostDto
@inject IConfiguration configuration
@{
    var hostAddress = configuration.GetSection("ApiServer").Value;
}
<nav id="breadcrumbs" class="breadcrumbs">
    <div class="container page-wrapper AllBreadcrumbs">
        <a asp-action="Index" asp-controller="Home" rel="homepage">Home</a>&nbsp;&nbsp;»&nbsp;&nbsp;
        <a asp-action="Index" asp-controller="Post" rel="post">Post</a>
    </div>
</nav>
<section class="w3l-blog-block2 mt-md-5">
    <div class="container mb-lg-4 BlogHomeLayout my-5">
        <div class="row my-3">
            <div class="col-md-9">
                <h3 class="section-title-left">All posts </h3>
            </div>
            <div class="col-md-3">
                <a asp-action="Create" asp-controller="Post" asp-area="" class="btn btn-style btn-outline ml-auto">Create new post</a>
            </div>
        </div>
        @if (Model?.Posts?.Count > 0)
        {
            <div class="row">
                @foreach (Post post in Model.Posts)
                {
                    <div class="col-lg-4 col-md-6 item mb-4">
                        <div class="card">
                            <div class="card-header p-0 position-relative blog-post-thumb">                               
                                <a class="post-thumbnail" asp-action="Detail" asp-route-id="@post.Id" aria-hidden="true" tabindex="-1">
                                    <img width="340" height="284"
                                         src="@(hostAddress + "/" + post.Thumbnail)"
                                         class="attachment-post-thumbnail size-post-thumbnail wp-post-image"
                                         alt="@post.Title" loading="lazy">
                                </a>


                            </div>
                            <div class="card-body p-0 blog-details">
                                <a asp-action="Detail" asp-route-id="@post.Id" rel="bookmark" class="blog-desc">
                                    @post.Title
                                </a>
                                <div class="author align-items-center mt-3 mb-1">
                                   <a class="url fn n"
                                          asp-action="Detail" asp-controller="Member" asp-route-id="@post.Author.Id">@post.Author.Username</a>

                                        in <a asp-action="Detail" asp-controller="Category" asp-area="" asp-route-id="@post.CategoryId" rel="category tag">Category @post.Category.Name</a>

                                    </div>

                                    <ul class="blog-meta">
                                        <li class="meta-item blog-lesson">
                                            <span class="meta-value"> @post.DateCreated.ToShortDateString()</span>

                                        </li>
                                        <li class="meta-item blog-students">
                                            <span class="meta-value">at @post.DateCreated.ToShortTimeString()</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
            </div>}
        else
        {
            <div class="text-center">
                <h5>Hiện không có bài viết nào</h5>
            </div>
        }

        @if (Model?.TotalPage > 1)
        {<div class="text-center">
                <pagination total-page="@Model.TotalPage" current-page="@Context.Request.Query["page"].FirstOrDefault()" url="/post/index?{0}"></pagination>
            </div>
        }
    </div>
</section>

WebApp/Views/Post/_Comments.cshtml
@model List<Comment>
@inject IConfiguration configuration
@{
    var hostAddress = configuration.GetSection("ApiServer").Value;
}

@foreach (var comment in Model)
{
    <div class="media" id="comment_@comment.Id">
        <div class="img-circle">
            <img src="@(hostAddress + "/" + comment.Author.AvatarUrl)" class="@comment.Author.FullName" alt="...">
        </div>
        <div class="media-body">
            <ul class="time-rply mb-2">
                <li>
                    <a asp-action="Detail" asp-controller="Member" asp-area="" asp-route-id="@comment.Author.Id" class="name mt-0 mb-2 d-block">@comment.Author.Username</a>
                    At @comment.DateCreate.ToShortTimeString() - @comment.DateCreate.ToShortDateString()
                </li>
            </ul>
            <p>
                @comment.Content
            </p>
            @if (int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)) == comment.AuthorId)
            {
                <div>
                    <a class="mr-3" asp-action="Edit" asp-controller="Comment" asp-area="" asp-route-id="@comment.Id">Edit</a>
                    <a asp-action="Delete" asp-controller="Comment" asp-area="" asp-route-id="@comment.Id">Delete</a>
                </div>
            }

        </div>
    </div>
}