WebApp/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    public class Category
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Bạn phải nhập tên danh mục")]
        [StringLength(64,MinimumLength =3,ErrorMessage = "{0} phải dài từ {2} đến {1} ký tự")]
        [Display(Name ="Tên danh mục")]
        public string Name { get; set; }
        public bool IsDeleted { get; set; } = false;
        [Display(Name = "Danh mục cha")]
        public int? ParentCategoryId { get; set; }
        public Category  ParentCategory { get; set; }
        public List<Category> ChildCategories { get; set; }
        public string Thumbnail { get; set; }
    }
}

WebApp/Areas/Dashboard/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using WebApp.Controllers;
using WebApp.Interfaces;
using WebApp.Models;

namespace WebApp.Areas.Dashboard.Controllers
{
    [Area("dashboard")]
    public class CategoryController : BaseController
    {
        public CategoryController(IRepositoryManager repository) : base(repository)
        {
        }

        // GET: CategoryController
        public async Task<ActionResult> Index()
        {
            return View(await _repository.Category.GetCategories());
        }

        // GET: CategoryController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            return View(await _repository.Category.GetCategoryById(id));
        }

        // GET: CategoryController/Create
        public async Task<ActionResult> CreateAsync()
        {
            ViewBag.categories = new SelectList(await _repository.Category.GetCategories(), "Id", "Name");
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Category category)
        {
            if (!ModelState.IsValid)
                return View();
            string token = User.FindFirstValue(ClaimTypes.Authentication);
            var result = await _repository.Category.Create(category, token);
            return RedirectToAction(nameof(Index));
            
        }

        // GET: CategoryController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            
            var category = await _repository.Category.GetCategoryById(id);
            if (category == null)
                return NotFound();
            ViewBag.categories = new SelectList(await _repository.Category.GetCategories(), "Id", "Name");
            return View(category);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Category category)
        {
            if (category.Id != id)
                return BadRequest();
            if (!ModelState.IsValid)
                return View();
            string token = User.FindFirstValue(ClaimTypes.Authentication);
            await _repository.Category.Edit(category, token);
            return RedirectToAction(nameof(Index));
        }

        // GET: CategoryController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            Category category = await _repository.Category.GetCategoryById(id);
            if (category == null)
                return NotFound();
            return View(category);
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            string token = User.FindFirstValue(ClaimTypes.Authentication);
            await _repository.Category.Delete(id, token);
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Areas/Manage/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using WebApp.Controllers;
using WebApp.Helper;
using WebApp.Interfaces;
using WebApp.Models;
using WebApp.Models.Response;

namespace WebApp.Areas.Dashboard.Controllers
{
    [Area("Manage")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : BaseController
    {
        public CategoryController(IRepositoryManager repository) : base(repository)
        {
        }

        public async Task<IActionResult> Index()
        {
            List<Category> categories = await _repository.Category.ManagerGetCategories(AccessToken);
            List<Category> listCategory = CategoryHelper.CreateTreeLevelCategory(categories);
            return View(listCategory);
        }
        public async Task<IActionResult> Create()
        {
            var categories= await _repository.Category.GetCategories();
            var selectListCategory = CategoryHelper.CreateSelectListCategory(categories);
            ViewBag.categories = new SelectList(selectListCategory, "Id", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category, IFormFile thumbnailImage)
        {
            if (!ModelState.IsValid)
            {
                var categories = await _repository.Category.GetCategories();
                var selectListCategory = CategoryHelper.CreateSelectListCategory(categories);                
                ViewBag.categories = new SelectList(selectListCategory, "Id", "Name");
                return View();
            }
            if (thumbnailImage != null && !string.IsNullOrEmpty(thumbnailImage.FileName))
            {
                category.Thumbnail = await UploadThumbnail(thumbnailImage);
            }
            var result = await _repository.Category.Create(category, AccessToken);
            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Edit(int id)
        {
            List<Category> categories = await _repository.Category.GetCategories();
            Category targetCategory = categories.Where(c => c.Id == id).FirstOrDefault();
            if (targetCategory == null)
                return NotFound();
            //A category cannot select itself or it's child as parent
            categories.Remove(targetCategory);
            categories = CategoryHelper.CreateTreeLevelCategory(categories);
            var selectListCategory = new List<Category>();
            CategoryHelper.CreateSelectListCategory(categories, selectListCategory, 0);
            ViewBag.categories = new SelectList(selectListCategory, "Id", "Name");
            return View(targetCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Category category, IFormFile thumbnailImage)
        {
            if (category.Id != id)
                return BadRequest();
            if (!ModelState.IsValid)
                return View();
            if (thumbnailImage != null && !string.IsNullOrEmpty(thumbnailImage.FileName))
            {
                category.Thumbnail = await UploadThumbnail(thumbnailImage);
            }
            ResponseModel response = await _repository.Category.Edit(category, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật danh mục thành công."
                });
                return RedirectToAction(nameof(Index));
            }
            HandleErrors(response);
            return View();

        }
        public async Task<IActionResult> Delete(int id)
        {
            ResponseModel response = await _repository.Category.Delete(id, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "warning",
                    Message = "Đã xóa danh mục."
                });
            }
            else
                HandleErrors(response);
            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Restore(int id)
        {
            ResponseModel response = await _repository.Category.Delete(id, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "info",
                    Message = "Đã khôi phục danh mục."
                });
            }
            else
                HandleErrors(response);
            return RedirectToAction(nameof(Index));

        }
    }
}

WebApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.DataTransferObject;
using WebApp.Interfaces;
using WebApp.Models;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class CategoryController : BaseController
    {
        public CategoryController(IRepositoryManager repository) : base(repository)
        {
        }

        public async Task<IActionResult> Index(int id)
        {
            List<Category> categories = await _repository.Category.GetCategories();
            return View(categories);
        }
        public async Task<IActionResult> Detail(int id, int page = 1)
        {
            Category category = await _repository.Category.GetCategoryById(id);
            if (category == null)
                return BadRequest();
            ListPostDto listPostFromCategory =   await _repository.Post.GetPostsFromCategory(id, page);

            ListPostFromCategoryDto viewModel = new ListPostFromCategoryDto
            {
                Category = category,
                Posts = listPostFromCategory.Posts,
                TotalPage = listPostFromCategory.TotalPage
            };
            return View(viewModel);
        }
    }
}

WebApp/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using WebApp.DataTransferObject;
using WebApp.Helper;
using WebApp.Interfaces;
using WebApp.Models;
using WebApp.Models.Response;

namespace WebApp.Controllers
{
    public class PostController : BaseController
    {
        public PostController(IRepositoryManager repository) : base(repository)
        {
        }
      
        public async Task<ActionResult> Index(int page = 1)
        {
            ListPostDto listPost = await _repository.Post.GetPosts(page);
            return View(listPost);
        }
       
        public async Task<ActionResult> Detail(int id)
        {
            Post post = await _repository.Post.GetPostById(id, countView: true);
            if (post == null)
                return NotFound();
            //Only author or admin/moderator can view inactive post detail
            if (post.IsActive == false && !User.IsInRole("Admin") && !User.IsInRole("Moderator"))
            {
                int userId;
                bool isUserIdExist = int.TryParse(User.FindFirstValue(System.Security.Claims.ClaimTypes.NameIdentifier), out userId);
                if(userId != post.AuthorId)
                    return BadRequest();
            }
            post.Comments = await _repository.Comment.GetCommentsByPostId(post.Id);
            return View(post);
        }
        
        [Authorize]
        public async Task<ActionResult> Create()
        {
            var categories = await _repository.Category.GetCategories();
            var selectListCategory = CategoryHelper.CreateSelectListCategory(categories);
            ViewBag.categories = new SelectList(selectListCategory, "Id", "Name");
            return View();
        }
      
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Post post, IFormFile thumbnailImage)
        {
            if (!ModelState.IsValid)
            {
                var categories = await _repository.Category.GetCategories();
                var selectListCategory = CategoryHelper.CreateSelectListCategory(categories);
                ViewBag.categories = new SelectList(selectListCategory, "Id", "Name");
                return View(post);
            }
            post.AuthorId = int.Parse(User.FindFirstValue(System.Security.Claims.ClaimTypes.NameIdentifier));
            post.DateCreated = DateTime.Now;
            if (thumbnailImage != null && !string.IsNullOrEmpty(thumbnailImage.FileName))
            {
                post.Thumbnail = await UploadThumbnail(thumbnailImage);
            }
            ResponseModel response = await _repository.Post.Create(post, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Bài viết của bạn đã được tạo và chờ duyệt."
                });
                return RedirectToAction(nameof(Index));
            }
            HandleErrors(response);
            return View(post);
        }
            
        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            Post post = await _repository.Post.GetPostById(id);
            if (post == null)
                return NotFound();                
            if (post.Author.Id == int.Parse(User.FindFirstValue(System.Security.Claims.ClaimTypes.NameIdentifier)) || User.IsInRole("Admin") || User.IsInRole("Moderator"))
            {
                var categories = await _repository.Category.GetCategories();
                var selectListCategory = CategoryHelper.CreateSelectListCategory(categories);
                ViewBag.categories = new SelectList(selectListCategory, "Id", "Name");
                return View(post);
            }
            return BadRequest();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, Post post, IFormFile thumbnailImage)
        {
            if (post.Id != id)
                return BadRequest();
            if (!ModelState.IsValid)
                return View(post);
            post.DateModifier = DateTime.Now;
            if (thumbnailImage != null && !string.IsNullOrEmpty(thumbnailImage.FileName))
            {
                post.Thumbnail = await UploadThumbnail(thumbnailImage);
            }
            ResponseModel response = await _repository.Post.Edit(post, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật bài viết thành công"
                });
                return RedirectToAction(nameof(Detail), new { id = id });
            }
            HandleErrors(response);
            return View(post);
        }
        
        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            Post post = await _repository.Post.GetPostById(id);
            if (post is null)
                return NotFound();
            //only author of post or admin can delete post            
            if (post.Author.Id == int.Parse(User.FindFirstValue(System.Security.Claims.ClaimTypes.NameIdentifier)) || User.IsInRole("Admin,Moderator"))
            {
                return View(post);
            }
            return BadRequest();

        }
               
        [Authorize]
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            ResponseModel response = await _repository.Post.Delete(id, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật trạng thái bài viết thành công"
                });
            }
            else
                HandleErrors(response);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Search(string keyword, int page = 1)
        {
            if (string.IsNullOrEmpty(keyword))
                return BadRequest();
            ListPostDto searchResult = await _repository.Post.SearchPost(keyword, page);
            return View(searchResult);
        }
        private void CreateSelectItems(List<Category> source, List<Category> des, int level)
        {
            string prefix = string.Concat(Enumerable.Repeat("----;", level));
            foreach (var category in source)
            {
                category.Name = prefix + category.Name;
                des.Add(category);
                if (category.ChildCategories?.Count > 0)
                {
                    CreateSelectItems(category.ChildCategories, des, level + 1);
                }
            }
        }
    }
}

WebApp/Views/Category/Detail.cshtml
@model ListPostFromCategoryDto
@inject IConfiguration configuration
@{
    var hostAddress = configuration.GetSection("ApiServer").Value;
}
<nav id="breadcrumbs" class="breadcrumbs">
    <div class="container page-wrapper AllBreadcrumbs">
        <a asp-action="Index" asp-controller="Home" rel="homepage">Home</a>&nbsp;&nbsp;»&nbsp;&nbsp;
        <a asp-action="Index" asp-controller="Category" rel="post">Category</a>
        &nbsp;&nbsp;»&nbsp;&nbsp;
        @Model.Category.Name
    </div>
</nav>
<section class="w3l-blog-block2 mt-md-5">
    <div class="container mb-lg-4 BlogHomeLayout my-5">
        <div class="row my-3">
            <div class="col-md-9">
                <h3 class="section-title-left">@Model.Category.Name </h3>
            </div>
            <div class="col-md-3">
                <a asp-action="Create" asp-controller="Post" asp-area="" class="btn btn-style btn-outline ml-auto">Create new post</a>
            </div>
        </div>
        @if (Model?.Posts?.Count > 0)
        {
            <div class="row">
                @foreach (Post post in Model.Posts)
                {
                    <div class="col-lg-4 col-md-6 item mb-4">
                        <div class="card">
                            <div class="card-header p-0 position-relative blog-post-thumb">
                                <a href="https://wp.w3layouts.com/designblog/2021/05/31/how-to-write-a-blog-post-a-step-by-step-guide/"></a>
                                <a class="post-thumbnail" asp-controller="Post" asp-area="" asp-action="Detail" asp-route-id="@post.Id" aria-hidden="true" tabindex="-1">
                                    <img width="340" height="284"
                                         src="@(hostAddress + "/" + post.Thumbnail)"
                                         class="attachment-post-thumbnail size-post-thumbnail wp-post-image"
                                         alt="@post.Title" loading="lazy">
                                </a>


                            </div>
                            <div class="card-body p-0 blog-details">
                                <a asp-action="Detail" asp-controller="Post" asp-area="" asp-route-id="@post.Id" rel="bookmark" class="blog-desc">
                                    @post.Title
                                </a>
                                <div class="author align-items-center mt-3 mb-1">
                                    <a href="https://wp.w3layouts.com/designblog/author/w3layouts/">
                                    </a><a class="url fn n"
                                           href="#">@post.Author.Username</a>
                                    </div>

                                    <ul class="blog-meta">
                                        <li class="meta-item blog-lesson">
                                            <span class="meta-value"> @post.DateCreated.ToShortDateString()</span>

                                        </li>
                                        <li class="meta-item blog-students">
                                            <span class="meta-value">at @post.DateCreated.ToShortTimeString()</span>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
            </div>}
        else
        {
            <div class="text-center">
                <h5>Hiện không có bài viết nào</h5>
            </div>
        }

        @if (Model?.TotalPage > 1)
        {<div class="text-center">
                <pagination total-page="@Model.TotalPage" current-page="@Context.Request.Query["page"].FirstOrDefault()" url="/category/detail/@Model.Category.Id?{0}"></pagination>
            </div>
        }
    </div>
</section>

WebApp/Views/Category/Index.cshtml
@model List<Category>
@inject IConfiguration configuration
@{
    var hostAddress = configuration.GetSection("ApiServer").Value;
}
<nav id="breadcrumbs" class="breadcrumbs">
    <div class="container page-wrapper AllBreadcrumbs">
        <a asp-action="Index" asp-controller="Home" rel="homepage">Home</a>&nbsp;&nbsp;»&nbsp;&nbsp;
        <a asp-action="Index" asp-controller="Category" rel="post">Category</a>
    </div>
</nav>
<section class="w3l-blog-block2 mt-md-5">
    <div class="container mb-lg-4 BlogHomeLayout my-5">
        <div class="my-3">          
                <h3 class="section-title-left">All category </h3>                   
        </div>
        @if (Model?.Count > 0)
        {
            <div class="row">
                @foreach (Category category in Model)
                {
                    <div class="col-lg-4 col-md-6 item mb-4">
                        <div class="card">
                            <div class="card-header p-0 position-relative blog-post-thumb">
                                <a href="https://wp.w3layouts.com/designblog/2021/05/31/how-to-write-a-blog-post-a-step-by-step-guide/"></a>
                                <a class="post-thumbnail" asp-action="Detail" asp-route-id="@category.Id" aria-hidden="true" tabindex="-1">
                                    <img width="340" height="284"
                                         src="@(hostAddress + "/" + category.Thumbnail)"
                                         class="attachment-post-thumbnail size-post-thumbnail wp-post-image"
                                         alt="@category.Name" loading="lazy">
                                </a>
                            </div>
                            <div class="card-body p-0 blog-details">
                                <a asp-action="Detail" asp-route-id="@category.Id" rel="bookmark" class="blog-desc">
                                    @category.Name
                                </a>
                            </div>
                        </div>
                    </div>
                }
            </div>}
        else
        {
            <div class="text-center">
                <h5>Hiện không có chuyên mục nào</h5>
            </div>
        }
    </div>
</section>