WebApp/Controllers/MemberController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebApp.Interfaces;
using WebApp.Models;
using WebApp.Models.Response;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    public class MemberController : BaseController
    {
        public MemberController(IRepositoryManager repository) : base(repository)
        {

        }

        public async Task<IActionResult> Index()
        {
            Member member = await _repository.Member.GetMemberById(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)), AccessToken);
            return View(member);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            Member member = await _repository.Member.GetMemberById(id);
            if (member == null)
                return NotFound();
            MemberDetailViewModel viewModel = new MemberDetailViewModel
            {
                Member = member,
                NumberOfComment = (await _repository.Comment.GetCommentsByMember(id)).Count,
                NumberOfPost = (await _repository.Post.GetPostsByMember(id)).Count
            };
            return View(viewModel);
        }

        public IActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordModel obj)
        {
            if (!ModelState.IsValid)
                return View();

            ResponseModel response = await _repository.Auth.ChangePassword(obj, AccessToken);            
            if (response is SuccessResponseModel)
            {
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật mật khẩu mới. Bạn cần đăng nhập lại."
                });
                return RedirectToAction("Login", "Account");
            }
            HandleErrors(response);
            return View();
        }

        public async Task<IActionResult> ListPost(int? id = null)
        {
            if (id == null)
                id = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            ListPostByMemberViewModel viewModel = new ListPostByMemberViewModel
            {
                Member = await _repository.Member.GetMemberById(id.Value),
                Posts = await _repository.Post.GetPostsByMember(id.Value, AccessToken)
            };
            return View(viewModel);
        }

        public async Task<IActionResult> ListComment(int? id = null)
        {
            if (id == null)
                id = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            ListCommentByMemberViewModel viewModel = new ListCommentByMemberViewModel
            {
                Member = await _repository.Member.GetMemberById(id.Value),
                Comments = await _repository.Comment.GetCommentsByMember(id.Value)
            };
            return View(viewModel);
        }
        public async Task<IActionResult> ChangeAboutMe()
        {
            Member member = await _repository.Member.GetMemberById(int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)), AccessToken);
            return View(new ChangeAboutMeModel
            {
                MemberId = member.Id,
                AboutMe = member.AboutMe
            });
        }
        [HttpPost]
        public async Task<IActionResult> ChangeAboutMe(ChangeAboutMeModel obj)
        {
            if (!ModelState.IsValid)
                return View();
            ResponseModel response = await _repository.Member.ChangeAboutMe(obj, AccessToken);            
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật giới thiệu bản thân."
                });
                return RedirectToAction(nameof(Index));
            }
            HandleErrors(response);
            return View();
        }
        public IActionResult ChangeAvatar()
        {
            int memberId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            return View(new ChangeAvatarModel
            {
                MemberId = memberId,
            });
        }
        [HttpPost]
        public async Task<IActionResult> ChangeAvatar(ChangeAvatarModel obj)
        {            
            if (!ModelState.IsValid)
                return View();
            MultipartFormDataContent content = new MultipartFormDataContent();
            if (obj.AvatarUpload != null)
            {
                if(obj.AvatarUpload.Length > (1024 * 1024))
                {
                    ModelState.AddModelError(string.Empty, "Hãy chọn hình ảnh có kích thước nhỏ hơn 1MB");
                    return View();
                }
                content.Add(new StringContent(obj.MemberId.ToString()), nameof(obj.MemberId));
                content.Add(new StreamContent(obj.AvatarUpload.OpenReadStream()), nameof(obj.AvatarUpload), obj.AvatarUpload.FileName);
            }
            ResponseModel response = await _repository.Member.ChangeAvatar(content, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật hình đại diện."
                });
                return RedirectToAction(nameof(Index));
            }
            HandleErrors(response);
            return View();
        }
    }
}

WebApp/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using WebApp.DataTransferObject;
using WebApp.Helper;
using WebApp.Interfaces;
using WebApp.Models;
using WebApp.Models.Response;

namespace WebApp.Controllers
{
    public class PostController : BaseController
    {
        public PostController(IRepositoryManager repository) : base(repository)
        {
        }
      
        public async Task<ActionResult> Index(int page = 1)
        {
            ListPostDto listPost = await _repository.Post.GetPosts(page);
            return View(listPost);
        }
       
        public async Task<ActionResult> Detail(int id)
        {
            Post post = await _repository.Post.GetPostById(id, countView: true);
            if (post == null)
                return NotFound();
            //Only author or admin/moderator can view inactive post detail
            if (post.IsActive == false && !User.IsInRole("Admin") && !User.IsInRole("Moderator"))
            {
                int userId;
                bool isUserIdExist = int.TryParse(User.FindFirstValue(System.Security.Claims.ClaimTypes.NameIdentifier), out userId);
                if(userId != post.AuthorId)
                    return BadRequest();
            }
            post.Comments = await _repository.Comment.GetCommentsByPostId(post.Id);
            return View(post);
        }
        
        [Authorize]
        public async Task<ActionResult> Create()
        {
            var categories = await _repository.Category.GetCategories();
            var selectListCategory = CategoryHelper.CreateSelectListCategory(categories);
            ViewBag.categories = new SelectList(selectListCategory, "Id", "Name");
            return View();
        }
      
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Post post, IFormFile thumbnailImage)
        {
            if (!ModelState.IsValid)
            {
                var categories = await _repository.Category.GetCategories();
                var selectListCategory = CategoryHelper.CreateSelectListCategory(categories);
                ViewBag.categories = new SelectList(selectListCategory, "Id", "Name");
                return View(post);
            }
            post.AuthorId = int.Parse(User.FindFirstValue(System.Security.Claims.ClaimTypes.NameIdentifier));
            post.DateCreated = DateTime.Now;
            if (thumbnailImage != null && !string.IsNullOrEmpty(thumbnailImage.FileName))
            {
                post.Thumbnail = await UploadThumbnail(thumbnailImage);
            }
            ResponseModel response = await _repository.Post.Create(post, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Bài viết của bạn đã được tạo và chờ duyệt."
                });
                return RedirectToAction(nameof(Index));
            }
            HandleErrors(response);
            return View(post);
        }
            
        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            Post post = await _repository.Post.GetPostById(id);
            if (post == null)
                return NotFound();                
            if (post.Author.Id == int.Parse(User.FindFirstValue(System.Security.Claims.ClaimTypes.NameIdentifier)) || User.IsInRole("Admin") || User.IsInRole("Moderator"))
            {
                var categories = await _repository.Category.GetCategories();
                var selectListCategory = CategoryHelper.CreateSelectListCategory(categories);
                ViewBag.categories = new SelectList(selectListCategory, "Id", "Name");
                return View(post);
            }
            return BadRequest();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, Post post, IFormFile thumbnailImage)
        {
            if (post.Id != id)
                return BadRequest();
            if (!ModelState.IsValid)
                return View(post);
            post.DateModifier = DateTime.Now;
            if (thumbnailImage != null && !string.IsNullOrEmpty(thumbnailImage.FileName))
            {
                post.Thumbnail = await UploadThumbnail(thumbnailImage);
            }
            ResponseModel response = await _repository.Post.Edit(post, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật bài viết thành công"
                });
                return RedirectToAction(nameof(Detail), new { id = id });
            }
            HandleErrors(response);
            return View(post);
        }
        
        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            Post post = await _repository.Post.GetPostById(id);
            if (post is null)
                return NotFound();
            //only author of post or admin can delete post            
            if (post.Author.Id == int.Parse(User.FindFirstValue(System.Security.Claims.ClaimTypes.NameIdentifier)) || User.IsInRole("Admin,Moderator"))
            {
                return View(post);
            }
            return BadRequest();

        }
               
        [Authorize]
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            ResponseModel response = await _repository.Post.Delete(id, AccessToken);
            if (response is SuccessResponseModel)
            {
                PushNotification(new NotificationOptions
                {
                    Type = "success",
                    Message = "Đã cập nhật trạng thái bài viết thành công"
                });
            }
            else
                HandleErrors(response);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Search(string keyword, int page = 1)
        {
            if (string.IsNullOrEmpty(keyword))
                return BadRequest();
            ListPostDto searchResult = await _repository.Post.SearchPost(keyword, page);
            return View(searchResult);
        }
        private void CreateSelectItems(List<Category> source, List<Category> des, int level)
        {
            string prefix = string.Concat(Enumerable.Repeat("----;", level));
            foreach (var category in source)
            {
                category.Name = prefix + category.Name;
                des.Add(category);
                if (category.ChildCategories?.Count > 0)
                {
                    CreateSelectItems(category.ChildCategories, des, level + 1);
                }
            }
        }
    }
}

WebApp/Areas/Dashboard/Views/Shared/_Layout.cshtml
<!--
Author: W3layouts
Author URL: http://w3layouts.com
-->
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Design Blog a Blog Category Bootstrap Responsive Website Template | Home : W3layouts</title>

    <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Template CSS -->
    <link rel="stylesheet" href="~/css/style-starter.css">
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/style-liberty.css" rel="stylesheet" />
    <link href="~/css/tlpfoodmenu.css" rel="stylesheet" />
</head>

<body>
    <!-- header -->
    <header class="w3l-header">
        <!--/nav-->
        <nav class="navbar navbar-expand-lg navbar-light fill px-lg-0 py-0 px-3">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <span class="fa fa-pencil-square-o"></span> Design Blog
                </a>
                <!-- if logo is image enable this
                        <a class="navbar-brand" href="#index.html">
                            <img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
                        </a> -->
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <!-- <span class="navbar-toggler-icon"></span> -->
                    <span class="fa icon-expand fa-bars"></span>
                    <span class="fa icon-close fa-times"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Post" asp-action="Index">Post</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="Dashboard" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="Dashboard" asp-controller="Comment" asp-action="Index">Comment</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="SeedData" asp-action="Index">Manage Data</a>
                        </li>
                        <li class="nav-item dropdown @@category__active">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Categories <span class="fa fa-angle-down"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item @@ls__active" href="lifestyle.html">Lifestyle posts</a>
                                <a class="dropdown-item @@cp__active" href="culture.html">Culture posts</a>
                            </div>
                        </li>
                        <li class="nav-item @@contact__active">
                            <a class="nav-link" href="contact.html">Contact</a>
                        </li>
                    </ul>

                    <!--/search-right-->
                    <div class="search-right mt-lg-0 mt-2">
                        <a href="#search" title="search"><span class="fa fa-search" aria-hidden="true"></span></a>
                        <!-- search popup -->
                        <div id="search" class="pop-overlay">
                            <div class="popup">
                                <h3 class="hny-title two">Search here</h3>
                                <form action="#" method="Get" class="search-box">
                                    <input type="search" placeholder="Search for blog posts" name="search"
                                           required="required" autofocus="">
                                    <button type="submit" class="btn">Search</button>
                                </form>
                                <a class="close" href="#close">×</a>
                            </div>
                        </div>
                        <!-- /search popup -->
                    </div>
                    <!--//search-right-->
                    <!-- author -->
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="header-author d-flex ml-lg-4 pl-2 mt-lg-0 mt-3">
                            <a class="img-circle img-circle-sm" href="#author">
                                <img src="~/images/author.jpg" class="img-fluid" alt="...">
                            </a>
                            <div class="align-self ml-3">
                                <a href="#author">
                                    <h5>Alexander</h5>
                                </a>
                                <span>Blog Writer</span>
                            </div>
                        </div>
                    }
                    else
                    { <div class="header-author d-flex ml-lg-4 pl-2 mt-lg-0 mt-3">
                            <a asp-action="Login" asp-controller="Member" class="btn btn-info mr-3">Login</a>
                            <a asp-action="Register" asp-controller="Member" class="btn btn-primary">Register</a>
                        </div>
                    }

                    <!-- // author-->
                </div>

                <!-- toggle switch for light and dark theme -->
                <!--<div class="mobile-position">
                    <nav class="navigation">
                        <div class="theme-switch-wrapper">
                            <label class="theme-switch" for="checkbox">
                                <input type="checkbox" id="checkbox">
                                <div class="mode-container">
                                    <i class="gg-sun"></i>
                                    <i class="gg-moon"></i>
                                </div>
                            </label>
                        </div>
                    </nav>
                </div>-->
                <!-- //toggle switch for light and dark theme -->
            </div>
        </nav>
        <!--//nav-->
    </header>
    <!-- //header -->
    @RenderBody()
    @*<div class="w3l-homeblock1 py-5">
            <div class="container">

            </div>
        </div>*@
    <!-- footer -->
    <footer class="w3l-footer-16">
        <div class="footer-content py-lg-5 py-4 text-center">
            <div class="container">
                <div class="copy-right">
                    <h6>
                        © 2020 Design Blog . Made with <span class="fa fa-heart" aria-hidden="true"></span>, Designed by
                        <a href="https://w3layouts.com">W3layouts</a>
                    </h6>
                </div>
                <ul class="author-icons mt-4">
                    <li>
                        <a class="facebook" href="#url"><span class="fa fa-facebook" aria-hidden="true"></span></a>
                    </li>
                    <li><a class="twitter" href="#url"><span class="fa fa-twitter" aria-hidden="true"></span></a></li>
                    <li>
                        <a class="google" href="#url"><span class="fa fa-google-plus" aria-hidden="true"></span></a>
                    </li>
                    <li><a class="linkedin" href="#url"><span class="fa fa-linkedin" aria-hidden="true"></span></a></li>
                    <li><a class="github" href="#url"><span class="fa fa-github" aria-hidden="true"></span></a></li>
                    <li><a class="dribbble" href="#url"><span class="fa fa-dribbble" aria-hidden="true"></span></a></li>
                </ul>
                <button onclick="topFunction()" id="movetop" title="Go to top">
                    <span class="fa fa-angle-up"></span>
                </button>
            </div>
        </div>

        <!-- move top -->
        <script>
            // When the user scrolls down 20px from the top of the document, show the button
            window.onscroll = function () {
                scrollFunction()
            };

            function scrollFunction() {
                if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                    document.getElementById("movetop").style.display = "block";
                } else {
                    document.getElementById("movetop").style.display = "none";
                }
            }

            // When the user clicks on the button, scroll to the top of the document
            function topFunction() {
                document.body.scrollTop = 0;
                document.documentElement.scrollTop = 0;
            }
        </script>
        <!-- //move top -->
    </footer>
    <!-- //footer -->
    <!-- Template JavaScript -->
    <script src="~/js/theme-change.js"></script>

    <script src="~/js/jquery-3.3.1.min.js"></script>

    <!-- disable body scroll which navbar is in active -->
    <script>
        $(function () {
            $('.navbar-toggler').click(function () {
                $('body').toggleClass('noscroll');
            })
        });
    </script>
    <!-- disable body scroll which navbar is in active -->

    <script src="~/js/bootstrap.min.js"></script>

</body>

</html>